server:
  port: 8004
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.atcast.entity
spring:
  application:
    name: Atguigu-SCMS-Hystrix-Dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_db_three
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7001.com:7001/eureka,www.eureka7002.com:7002/eureka