server:
  port: 8001
mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.atcast.entity
spring:
  application:
    name: Atguigu-SCMS-Dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_db_one
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka